spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL_PROD}
    username: ${SPRING_DATASOURCE_USERNAME_PROD}
    password: ${SPRING_DATASOURCE_PASSWORD_PROD}
    driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
  hibernate:
    ddl-auto: none

aws:
  region: ap-northeast-2
  s3:
    bucket-name: runninghandai-bucket

logging:
  file:
    name: /home/ubuntu/runninghandai/log/app.log