spring:
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: none # 기본값은 none (환경에 따라 오버라이딩)
    properties:
      hibernate:
        default_batch_fetch_size: 100
sever:
  port: ${PORT:8080}

# 헬스 체크
management:
  endpoints:
    web:
      base-path: /