spring:
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 100 # JDBC Batch Insert 활성화
        order_inserts: true
        order_updates: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          max-tokens: 2000
      input-max-tokens: 126000

  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: ${S3_BUCKET_NAME}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${KAKAO_API_KEY}
            client-secret: ${KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
          naver:
            client-name: naver
            client-id: ${NAVER_API_KEY}
            client-secret: ${NAVER_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: email
          google:
            client-id: ${GOOGLE_API_KEY}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email
        provider:
          kakao:
            # (1) 사용자가 카카오 로그인 클릭 시
            # (2) 인가코드를 서버에 전달 (redirect-uri)
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            # (3) 카카오 Access Token 발급
            token-uri: https://kauth.kakao.com/oauth/token
            # (4) 카카오 Access Token으로 사용자 정보 반환
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
            scope: account_email
          naver:
            # (1) 사용자가 네이버 로그인 클릭 시
            # (2) 인가코드를 서버에 전달 (redirect-uri)
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            # (3) 네이버 Access Token 발급
            token-uri: https://nid.naver.com/oauth2.0/token
            # (4) 네이버 Access Token으로 사용자 정보 반환
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  servlet:
    multipart:
      max-file-size: 5MB

server:
  port: ${PORT:8080}
  forward-headers-strategy: NATIVE

management:
  endpoints:
    web:
      base-path: /

external:
  api:
    durunubi:
      base-url: http://apis.data.go.kr/B551011/Durunubi
      service-key: ${DURUNUBI_SERVICE_KEY}

springdoc:
  default-produces-media-type: application/json
  paths-to-exclude:
    - /api/admin/** # Swagger UI에서 제외하는 엔드포인트
  swagger-ui:
    path: /teamchuck/docs
  api-docs:
    path: /teamchuck/v3/api-docs

jwt:
  secret-key: ${JWT_SECRET_KEY}
  # Access Token: 30분 (1,800,000ms)
  access-expiration: 1800000
  # Refresh Token: 14일 (1,209,600,000ms)
  refresh-expiration: 1209600000

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [ReqId: %X{requestId:-EMPTY}] [ClientIp: %X{clientIp:-EMPTY}] - %msg%n"
  level:
    root: INFO

course:
  simplification:
    distance-tolerance: 0.0001 # 경로 단순화 허용 오차 (RDP 알고리즘), 약 10m
